services:

  generator:
    build: .
    command:
      - cs.mff.uk.simek.generator.Generator
    environment:
      CONFIG_FILE: /oxm_config.yaml
    volumes:
      - ./data:/data
      - ./oxm_config.yaml:/oxm_config.yaml:ro

  mongo:
    image: mongo:8
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  importer:
    build: .
    command:
      - cs.mff.uk.simek.importer.Importer
    environment:
      CONFIG_FILE: /oxm_config.yaml
    volumes:
      - ./data:/data
      - ./oxm_config.yaml:/oxm_config.yaml:ro
    depends_on:
      generator:
        condition: service_completed_successfully
      mongo:
        condition: service_started

volumes:
  mongo-data:
